// <auto-generated />
using System;
using CE_API_V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CE_API_V2.Migrations
{
    [DbContext(typeof(CEContext))]
    [Migration("20230626130715_AddedUserModel")]
    partial class AddedUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CE_API_V2.Models.Biomarkers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AceInhibitor")
                        .HasColumnType("bit");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("Alat")
                        .HasColumnType("real");

                    b.Property<float>("Albumin")
                        .HasColumnType("real");

                    b.Property<float>("AlkalinePhosphate")
                        .HasColumnType("real");

                    b.Property<bool>("Betablocker")
                        .HasColumnType("bit");

                    b.Property<float>("Bilirubin")
                        .HasColumnType("real");

                    b.Property<bool>("CaAntagonist")
                        .HasColumnType("bit");

                    b.Property<int>("ChestPain")
                        .HasColumnType("int");

                    b.Property<float>("Cholesterol")
                        .HasColumnType("real");

                    b.Property<int>("ClinicalSetting")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Diabetes")
                        .HasColumnType("int");

                    b.Property<float>("DiastolicBloodPressure")
                        .HasColumnType("real");

                    b.Property<bool>("Diuretic")
                        .HasColumnType("bit");

                    b.Property<float>("Glucose")
                        .HasColumnType("real");

                    b.Property<float>("Hdl")
                        .HasColumnType("real");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<float>("HsTroponinT")
                        .HasColumnType("real");

                    b.Property<float>("Ldl")
                        .HasColumnType("real");

                    b.Property<float>("Leukocytes")
                        .HasColumnType("real");

                    b.Property<float>("Mchc")
                        .HasColumnType("real");

                    b.Property<int>("Nicotine")
                        .HasColumnType("int");

                    b.Property<bool>("OganicNitrate")
                        .HasColumnType("bit");

                    b.Property<float>("PancreaticAmylase")
                        .HasColumnType("real");

                    b.Property<bool>("PriorCAD")
                        .HasColumnType("bit");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RestingECG")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<bool>("Statin")
                        .HasColumnType("bit");

                    b.Property<float>("SystolicBloodPressure")
                        .HasColumnType("real");

                    b.Property<bool>("TcAggInhibitor")
                        .HasColumnType("bit");

                    b.Property<float>("Urea")
                        .HasColumnType("real");

                    b.Property<float>("UricAcid")
                        .HasColumnType("real");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("Biomarkers");
                });

            modelBuilder.Entity("CE_API_V2.Models.ScoringRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScoringRequests");
                });

            modelBuilder.Entity("CE_API_V2.Models.ScoringResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("classifier_class")
                        .HasColumnType("int");

                    b.Property<double?>("classifier_score")
                        .HasColumnType("float");

                    b.Property<int?>("classifier_sign")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ScoringResponses");
                });

            modelBuilder.Entity("CE_API_V2.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActiveDirectoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicalSetting")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalSpecialisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitLabValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CE_API_V2.Models.Biomarkers", b =>
                {
                    b.HasOne("CE_API_V2.Models.ScoringRequest", "Request")
                        .WithOne("Biomarkers")
                        .HasForeignKey("CE_API_V2.Models.Biomarkers", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CE_API_V2.Models.ScoringResponse", b =>
                {
                    b.HasOne("CE_API_V2.Models.ScoringRequest", "Request")
                        .WithOne("Response")
                        .HasForeignKey("CE_API_V2.Models.ScoringResponse", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CE_API_V2.Models.ScoringRequest", b =>
                {
                    b.Navigation("Biomarkers");

                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
